/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.mincultura.vistas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YStark
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuVerMuseos = new javax.swing.JMenuItem();
        mnuPinturas = new javax.swing.JMenu();
        mnuVerPinturas = new javax.swing.JMenuItem();
        mnuArtistas = new javax.swing.JMenu();
        mnuVerArtistas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ministerio de cultura");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        ImageIcon mincultura = new ImageIcon(getClass().getResource("/gov/mincultura/assets/logo-mincultura.png"));
        ImageIcon icon = new ImageIcon(mincultura.getImage().getScaledInstance(600, 100, Image.SCALE_DEFAULT));
        jLabel2.setIcon(icon);

        jMenu2.setText("Museos");

        mnuVerMuseos.setText("Ver");
        mnuVerMuseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerMuseosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuVerMuseos);

        jMenuBar1.add(jMenu2);

        mnuPinturas.setText("Pinturas");

        mnuVerPinturas.setText("Ver");
        mnuVerPinturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerPinturasActionPerformed(evt);
            }
        });
        mnuPinturas.add(mnuVerPinturas);

        jMenuBar1.add(mnuPinturas);

        mnuArtistas.setText("Artistas");

        mnuVerArtistas.setText("Ver");
        mnuVerArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerArtistasActionPerformed(evt);
            }
        });
        mnuArtistas.add(mnuVerArtistas);

        jMenuBar1.add(mnuArtistas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVerMuseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerMuseosActionPerformed
        // TODO add your handling code here:
        frmMuseos fmrMuseo = new frmMuseos();
        fmrMuseo.setLocationRelativeTo(this);
        fmrMuseo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuVerMuseosActionPerformed

    private void mnuVerPinturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerPinturasActionPerformed
        // TODO add your handling code here:
        frmPinturas fmrPintura = new frmPinturas();
        fmrPintura.setLocationRelativeTo(this);
        fmrPintura.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuVerPinturasActionPerformed

    private void mnuVerArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerArtistasActionPerformed
        // TODO add your handling code here:
        frmArtistas fmrArtista = new frmArtistas();
        fmrArtista.setLocationRelativeTo(this);
        fmrArtista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuVerArtistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuArtistas;
    private javax.swing.JMenu mnuPinturas;
    private javax.swing.JMenuItem mnuVerArtistas;
    private javax.swing.JMenuItem mnuVerMuseos;
    private javax.swing.JMenuItem mnuVerPinturas;
    // End of variables declaration//GEN-END:variables
}
